services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build-unit-test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=/cache/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

compile:
  stage: build-unit-test
  image: $CI_REGISTRY/research/coe-maven-centos:latest
  script:
    - mvn $MAVEN_CLI_OPTS clean test
  tags:
    - docker

deploy:
  stage: deploy
  image: $CI_REGISTRY/research/coe-maven-centos:latest
  script:
    - mvn $MAVEN_CLI_OPTS clean javadoc:javadoc deploy -Pcoe
  tags:
    - docker
  only:
    - master
