stages:
  - build-unit-test
  - jars
#  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=/cache/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  REGISTRY_RELEASE_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_BUILD_REF_NAME

compile:
  stage: build-unit-test
  image: maven:3-jdk-8
  script:
    - mvn $MAVEN_CLI_OPTS clean test
  tags:
    - docker

install:
  stage: jars
  image: maven:3-jdk-8
  artifacts:
    expire_in: 1 day
    paths:
      - artifacts/
  script:
    - mkdir artifacts
    - mvn $MAVEN_CLI_OPTS install -DskipTests
    - find storers/executables/target -name "*uberjar*" -exec cp '{}' 'artifacts/store-uberjar.jar' \;
  tags:
    - docker

# deploy:
#   stage: deploy
#   image: maven:3-jdk-8
#   script:
#     - mvn $MAVEN_CLI_OPTS clean javadoc:javadoc deploy -Pcoe
#   tags:
#     - docker
#   only:
#     - master
